<?php

declare(strict_types=1);

return [
  'GET' => [
    '/' => ['App\\Controllers\\HomeController', 'index'],
    '/about' => ['App\\Controllers\\HomeController', 'about'],
    '/home/about' => ['App\\Controllers\\HomeController', 'about'],
    '/contact' => ['App\\Controllers\\HomeController', 'contact'],
    '/faq' => ['App\\Controllers\\HomeController', 'faq'],
    '/privacy' => ['App\\Controllers\\HomeController', 'privacy'],
    '/terms' => ['App\\Controllers\\HomeController', 'terms'],
    '/login' => ['App\\Controllers\\AuthController', 'showLogin'],
    '/register' => ['App\\Controllers\\AuthController', 'showRegister'],
    '/logout' => ['App\\Controllers\\AuthController', 'logout'],
    '/forgot-password' => ['App\\Controllers\\AuthController', 'showForgotPassword'],
    '/reset-password' => ['App\\Controllers\\AuthController', 'showResetPassword'],
    '/verify-email' => ['App\\Controllers\\AuthController', 'verifyEmail'],
    '/resend-verification' => ['App\\Controllers\\AuthController', 'showResendVerification'],
    '/dashboard' => ['App\\Controllers\\DashboardController', 'index'],
    '/admin' => ['App\\Controllers\\AdminController', 'index'],
    '/vendor' => ['App\\Controllers\\VendorDashboardController', 'index'],
    '/vendor/apply' => ['App\\Controllers\\VendorController', 'apply'],
    '/vendor/products/new' => ['App\\Controllers\\ProductController', 'create'],
    '/vendor/products' => ['App\\Controllers\\ProductController', 'vendorIndex'],
    '/vendor/products/edit' => ['App\\Controllers\\ProductController', 'edit'],
    '/vendor/products/view' => ['App\\Controllers\\ProductController', 'vendorShow'],
    '/vendor/markets/apply' => ['App\\Controllers\\VendorController', 'marketApply'],
    '/vendor-market-applications' => ['App\\Controllers\\VendorController', 'marketHistory'],
    '/super-admin' => ['App\\Controllers\\SuperAdminController', 'index'],
    '/admin-management' => ['App\\Controllers\\SuperAdminController', 'manageAdmins'],
    '/admin/vendor-applications' => ['App\\Controllers\\AdminController', 'vendorApplications'],
    '/admin/vendor-application' => ['App\\Controllers\\AdminController', 'vendorApplicationShow'],
    '/admin/market-applications' => ['App\\Controllers\\AdminController', 'marketApplications'],
    '/admin/market-dates' => ['App\\Controllers\\AdminController', 'marketDates'],
    '/admin/market-dates/new' => ['App\\Controllers\\AdminController', 'showCreateMarketDate'],
    '/admin/market-dates/edit' => ['App\\Controllers\\AdminController', 'showEditMarketDate'],
    '/admin/reviews' => ['App\\Controllers\\AdminController', 'reviewManagement'],
    '/vendors' => ['App\\Controllers\\VendorController', 'index'],
    '/products' => ['App\\Controllers\\ProductController', 'index'],
    '/markets' => ['App\\Controllers\\MarketController', 'index'],
  ],
  'POST' => [
    '/login' => ['App\\Controllers\\AuthController', 'login'],
    '/register' => ['App\\Controllers\\AuthController', 'register'],
    '/forgot-password' => ['App\\Controllers\\AuthController', 'sendResetLink'],
    '/reset-password' => ['App\\Controllers\\AuthController', 'resetPassword'],
    '/resend-verification' => ['App\\Controllers\\AuthController', 'resendVerification'],
    '/vendor/apply' => ['App\\Controllers\\VendorController', 'submitApplication'],
    '/vendor/products' => ['App\\Controllers\\ProductController', 'store'],
    '/vendor/products/edit' => ['App\\Controllers\\ProductController', 'update'],
    '/vendor/products/delete' => ['App\\Controllers\\ProductController', 'destroy'],
    '/vendor/markets/apply' => ['App\\Controllers\\VendorController', 'submitMarketApply'],
    '/vendor/reviews/submit' => ['App\\Controllers\\VendorController', 'submitReview'],
    '/vendor/reviews/respond' => ['App\\Controllers\\VendorController', 'respondToReview'],
    '/admin/vendor-applications' => ['App\\Controllers\\AdminController', 'handleVendorApplication'],
    '/admin/market-applications' => ['App\\Controllers\\AdminController', 'handleMarketApplication'],
    '/admin/market-dates' => ['App\\Controllers\\AdminController', 'createMarketDate'],
    '/admin/market-dates/edit' => ['App\\Controllers\\AdminController', 'updateMarketDate'],
    '/admin/market-dates/delete' => ['App\\Controllers\\AdminController', 'deleteMarketDate'],
    '/admin/reviews/handle' => ['App\\Controllers\\AdminController', 'handleReview'],
  ],
];
